//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR_Preventive_ClientName.dbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_CALL
    {
        public decimal ID { get; set; }
        public string CALLID { get; set; }
        public string PARENTCALLID { get; set; }
        public string MERGECALLID { get; set; }
        public Nullable<int> MERGETYPE { get; set; }
        public string CONNID { get; set; }
        public Nullable<decimal> CONNIDNUM { get; set; }
        public Nullable<int> SWITCHCALLID { get; set; }
        public string IRID { get; set; }
        public string ROOTIRID { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<int> CALLTYPE { get; set; }
        public Nullable<int> MEDIATYPE { get; set; }
        public Nullable<int> SWITCHID { get; set; }
        public Nullable<int> TENANTID { get; set; }
        public string CALLANI { get; set; }
        public string CALLDNIS { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<int> CREATED_TS { get; set; }
        public Nullable<int> CREATED_TCODE { get; set; }
        public Nullable<System.DateTime> TERMINATED { get; set; }
        public Nullable<int> TERMINATED_TS { get; set; }
        public Nullable<int> TERMINATED_TCODE { get; set; }
        public Nullable<int> GSYS_DOMAIN { get; set; }
        public Nullable<int> GSYS_PARTITION { get; set; }
        public Nullable<int> GSYS_SYS_ID { get; set; }
        public Nullable<long> GSYS_SEQ { get; set; }
        public Nullable<long> GSYS_USEQ { get; set; }
        public Nullable<System.DateTime> GSYS_TS { get; set; }
        public Nullable<int> GSYS_TC { get; set; }
        public string GSYS_EXT_VCH1 { get; set; }
        public string GSYS_EXT_VCH2 { get; set; }
        public Nullable<int> GSYS_EXT_INT1 { get; set; }
        public Nullable<int> GSYS_EXT_INT2 { get; set; }
    }
}
