//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR_Preventive_ClientName.dbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_PARTY
    {
        public decimal ID { get; set; }
        public string PARTYID { get; set; }
        public string PARTYGUID { get; set; }
        public int TYPE { get; set; }
        public int PROLE { get; set; }
        public string PARENTPARTYID { get; set; }
        public Nullable<int> PARENTLINKTYPE { get; set; }
        public string CALLID { get; set; }
        public int STATE { get; set; }
        public string ENDPOINTDN { get; set; }
        public int ENDPOINTID { get; set; }
        public int ENDPOINTTYPE { get; set; }
        public Nullable<int> TENANTID { get; set; }
        public Nullable<int> AGENTID { get; set; }
        public Nullable<int> CCEVENT { get; set; }
        public Nullable<int> CCEVENTCAUSE { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<int> CREATED_TS { get; set; }
        public Nullable<int> CREATED_TCODE { get; set; }
        public Nullable<System.DateTime> TERMINATED { get; set; }
        public Nullable<int> TERMINATED_TS { get; set; }
        public Nullable<int> TERMINATED_TCODE { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public Nullable<int> LASTCHANGE_TS { get; set; }
        public Nullable<int> LASTCHANGE_TCODE { get; set; }
        public Nullable<int> GSYS_DOMAIN { get; set; }
        public Nullable<int> GSYS_PARTITION { get; set; }
        public Nullable<int> GSYS_SYS_ID { get; set; }
        public Nullable<long> GSYS_SEQ { get; set; }
        public Nullable<long> GSYS_USEQ { get; set; }
        public Nullable<System.DateTime> GSYS_TS { get; set; }
        public Nullable<int> GSYS_TC { get; set; }
        public string GSYS_EXT_VCH1 { get; set; }
        public string GSYS_EXT_VCH2 { get; set; }
        public Nullable<int> GSYS_EXT_INT1 { get; set; }
        public Nullable<int> GSYS_EXT_INT2 { get; set; }
        public string TS_PARENTPARTYGUID { get; set; }
    }
}
