//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR_Preventive_ClientName.dbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_PARTY_STAT
    {
        public decimal ID { get; set; }
        public string PARTYID { get; set; }
        public Nullable<int> TT_ALERTING { get; set; }
        public Nullable<int> TT_CONNECTED { get; set; }
        public Nullable<int> TT_HOLD { get; set; }
        public Nullable<int> TT_QUEUED { get; set; }
        public Nullable<int> TT_ACW { get; set; }
        public Nullable<int> CNT_ALERTING { get; set; }
        public Nullable<int> CNT_CONNECTED { get; set; }
        public Nullable<int> CNT_HOLD { get; set; }
        public Nullable<int> CNT_QUEUED { get; set; }
        public Nullable<int> CNT_ACW { get; set; }
        public Nullable<int> TT_ON_ALERT { get; set; }
        public Nullable<int> TT_ON_HOLD { get; set; }
        public Nullable<int> TT_ON_QUEUE { get; set; }
        public Nullable<int> TT_ON_CONNECTED { get; set; }
        public Nullable<int> T_DURATION { get; set; }
        public Nullable<int> GSYS_DOMAIN { get; set; }
        public Nullable<int> GSYS_PARTITION { get; set; }
        public Nullable<int> GSYS_SYS_ID { get; set; }
        public Nullable<long> GSYS_SEQ { get; set; }
        public Nullable<long> GSYS_USEQ { get; set; }
        public Nullable<System.DateTime> GSYS_TS { get; set; }
        public Nullable<int> GSYS_TC { get; set; }
        public string GSYS_EXT_VCH1 { get; set; }
        public string GSYS_EXT_VCH2 { get; set; }
        public Nullable<int> GSYS_EXT_INT1 { get; set; }
        public Nullable<int> GSYS_EXT_INT2 { get; set; }
        public Nullable<int> PM_EXT_1 { get; set; }
        public Nullable<int> PM_EXT_2 { get; set; }
        public Nullable<int> PM_EXT_3 { get; set; }
        public Nullable<int> PM_EXT_4 { get; set; }
        public Nullable<int> PM_EXT_5 { get; set; }
        public Nullable<int> PM_EXT_6 { get; set; }
        public Nullable<int> PM_EXT_7 { get; set; }
        public Nullable<int> PM_EXT_8 { get; set; }
        public Nullable<int> PM_EXT_9 { get; set; }
        public Nullable<int> PM_EXT_10 { get; set; }
    }
}
